name: Deploy MERN Frontend

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest .

      - name: Publish Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

      - name: Delete old container
        run: docker rm -f reactjs-app-container

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name reactjs-app-container ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest
